apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tm-cloud.backend-controller.fullname" . }}
  labels:
    {{- include "tm-cloud.backend-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "tm-cloud.backend-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "tm-cloud.backend-controller.fullname" . }}

