# Default values for imagepullsecret-patcher.

replicaCount: 1

image:
  repository: "quay.io/titansoft/imagepullsecret-patcher"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

dockerconfigjson: ""

imagePullSecretName: "image-pull-secret"

excludedNamespaces: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 0.1
    memory: 15Mi
  limits:
    cpu: 0.2
    memory: 30Mi

nodeSelector: {}

tolerations: []

affinity: {}
