apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-serving-operator
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "knative-operator.fullname" . }}-serving-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "knative-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-serving-operator-aggregated
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "knative-operator.fullname" . }}-serving-operator-aggregated
subjects:
  - kind: ServiceAccount
    name: {{ include "knative-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# TODO: Consider restriction of non-aggregated role to knativeeventing namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-eventing-operator
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "knative-operator.fullname" . }}-eventing-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "knative-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-eventing-operator-aggregated
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "knative-operator.fullname" . }}-eventing-operator-aggregated
subjects:
  - kind: ServiceAccount
    name: {{ include "knative-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
