{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operatorNamespace }}
  labels:
    {{- include "istio-operator.labels" . | nindent 4 }}
    istio-operator-managed: Reconcile
    istio-injection: disabled
{{- end }}
