apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tm-cloud.triggerflow.fullname" . }}
  labels:
    {{- include "tm-cloud.triggerflow.labels" . | nindent 4 }}
data:
  componentComparer: |
    {
      "deepEqual": [
        {
          "group": "serving.knative.dev",
          "version": "*",
          "kind": "Service",
          "paths": [".spec.template.spec.containers[0].env"]
        },
        {
          "group": "eventing.knative.dev",
          "version": "*",
          "kind": "Trigger",
          "paths": [".spec.filter.attributes"]
        },
        {
          "group": "sources.triggermesh.io",
          "version": "*",
          "kind": "*",
          "paths": [".spec"]
        },
        {
          "group": "targets.triggermesh.io",
          "version": "*",
          "kind": "*",
          "paths": [".spec"]
        },
        {
          "group": "extensions.triggermesh.io",
          "version": "*",
          "kind": "Function",
          "paths": [".spec"]
        },
        {
          "group": "flow.triggermesh.io",
          "version": "*",
          "kind": "Splitter",
          "paths": [".spec"]
        }
      ]
    }

  status: |
    {
      "parserMapping": {
        "deployment": [
          {
            "group": "apps",
            "version": "v1",
            "kind": "Deployment"
          }
        ],

        "knative": [
          {
            "group": "serving.knative.dev",
            "version": "*",
            "kind": "*"
          },
          {
            "group": "eventing.knative.dev",
            "version": "*",
            "kind": "*"
          },
          {
            "group": "flows.knative.dev",
            "version": "*",
            "kind": "*"
          },
          {
            "group": "messaging.knative.dev",
            "version": "*",
            "kind": "*"
          },

          {
            "group": "sources.knative.dev",
            "version": "*",
            "kind": "*"
          },
          {
            "group": "targets.triggermesh.io",
            "version": "*",
            "kind": "*"
          },
          {
            "group": "sources.triggermesh.io",
            "version": "*",
            "kind": "*"
          },
          {
            "group": "flow.triggermesh.io",
            "version": "*",
            "kind": "*"
          },
          {
            "group": "extensions.triggermesh.io",
            "version": "*",
            "kind": "*"
          }
        ]
      }
    }
