apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tm-cloud.event-sources.fullname" . }}
  labels:
    {{- include "tm-cloud.event-sources.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tm-cloud.event-sources.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "tm-cloud.event-sources.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
      annotations:
        checksum/knative-configs: {{ include (print .Template.BasePath "/knative/configmap.yaml") . | sha256sum }}
    spec:
{{- include "tm-cloud.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "tm-cloud.event-sources.fullname" . }}
      containers:
      - name: controller
        image: "{{ .Values.global.image.registry }}/triggermesh-private/event-sources-controller:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Logging/observability configuration
        - name: CONFIG_LOGGING_NAME
          value: {{ include "tm-cloud.knative-configs.fullname" . }}-config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ include "tm-cloud.knative-configs.fullname" . }}-config-observability
        - name: CONFIG_LEADERELECTION_NAME
          value: {{ include "tm-cloud.knative-configs.fullname" . }}-config-leader-election
        - name: METRICS_DOMAIN
          value: triggermesh.io/sources
        # Source adapters
        - name: AZUREEVENTHUBSOURCE_IMAGE
          value: "{{ .Values.global.image.registry }}/triggermesh-private/azureeventhubsource-adapter:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
        - name: GOOGLECLOUDPUBSUBSOURCE_IMAGE
          value: "{{ .Values.global.image.registry }}/triggermesh-private/googlecloudpubsubsource-adapter:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
        - name: OCIMETRICSSOURCE_IMAGE
          value: "{{ .Values.global.image.registry }}/triggermesh-private/ocimetricssource-adapter:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
        - name: SALESFORCESOURCE_IMAGE
          value: "{{ .Values.global.image.registry }}/triggermesh-private/salesforcesource-adapter:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
        - name: TWILIOSOURCE_IMAGE
          value: "{{ .Values.global.image.registry }}/triggermesh-private/twiliosource-adapter:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: profiling
          containerPort: 8008
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
