apiVersion: flow.triggermesh.io/v1alpha1
kind: BridgeCatalogEntry
metadata:
  name: gitlab-elasticsearch
  labels:
    {{- include "tm-cloud.bridgecatalogentries.labels" . | nindent 4 }}

title: GitLab to Elasticsearch
shortDescription: Send GitLab events to Elasticsearch
fullDescription: >-
  This Bridge forwards GitLab events from a specific repository to be indexed
  by Elasticsearch.

components:
# Event Broker
- apiVersion: eventing.knative.dev/v1
  kind: Broker
  metadata:
    name: events
# Event Source
- apiVersion: sources.knative.dev/v1alpha1
  kind: GitLabSource
  metadata:
    name: gitlab
  spec:
    eventTypes:
    - push_events
    - issues_events
    projectUrl: ''
    accessToken:
      secretKeyRef:
        name: gitlabcreds
        key: accessToken
    secretToken:
      secretKeyRef:
        name: gitlabcreds
        key: secretToken
    sink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: events
# Event Target
- apiVersion: targets.triggermesh.io/v1alpha1
  kind: ElasticsearchTarget
  metadata:
    name: elastic
  spec:
    connection:
      addresses:
        - ''
      skipVerify: true
      username: elastic
      password:
        secretKeyRef:
          name: elastic-creds
          key: password
    indexName: ''
# Target Trigger
- apiVersion: eventing.knative.dev/v1
  kind: Trigger
  metadata:
    name: elastic
  spec:
    broker: events
    subscriber:
      ref:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: ElasticsearchTarget
        name: elastic
