apiVersion: v1
kind: Service
metadata:
  name: {{ include "tm-cloud.event-sources.fullname" . }}-webhook
  labels:
    {{- include "tm-cloud.event-sources.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    {{- include "tm-cloud.event-sources.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
