apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tm-cloud.event-sources.fullname" . }}-webhook
  labels:
    contrib.eventing.knative.dev/release: devel
    {{- include "tm-cloud.event-sources.labels" . | nindent 4 }}
rules:
# Sources admin
- apiGroups:
  - sources.triggermesh.io
  resources:
  - azureeventhubsources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Sources finalizer
- apiGroups:
  - sources.triggermesh.io
  resources:
  - azureeventhubsourcesources/finalizers
  verbs:
  - patch

# Source statuses update
- apiGroups:
  - sources.triggermesh.io
  resources:
  - azureeventhubsources/status
  verbs:
  - update

# Events admin
- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# For manipulating certs into secrets.
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - create
    - update
    - list
    - watch

# For actually registering our webhook.
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - "mutatingwebhookconfigurations"
  - "validatingwebhookconfigurations"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - {{ include "tm-cloud.event-sources.fullname" . }}-webhook.defaultingwebhook.00-of-01
  - {{ include "tm-cloud.event-sources.fullname" . }}-webhook.validationwebhook.00-of-01
  - {{ include "tm-cloud.event-sources.fullname" . }}-webhook.webhookcertificates.00-of-01
  resources:
  - leases
  verbs:
  - get
  - update
