apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tekton-operator.fullname" . }}
  namespace: {{.Values.operatorNamespace}}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
    operator.tekton.dev/release: devel
    version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tekton-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tekton-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tekton-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: IMAGE_PIPELINES_PROXY
              value: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/webhook:v0.23.0-2@sha256:f359bf33d2cb6073f1b19b04cd76f6d341aa5a2ddd485c9a10a5b234d8fb4db0
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ include "tekton-operator.fullname" . }}
            - name: CONFIG_LOGGING_NAME
              value: {{ include "tekton-operator.fullname" . }}-config-logging
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
