apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imagepullsecret-patcher.fullname" . }}
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
type: Opaque
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | b64enc }}
