{{- if not .Values.frontend.ingress.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tm-cloud.frontend.fullname" . }}-nginx
  labels:
    {{- include "tm-cloud.frontend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tm-cloud.frontend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "tm-cloud.frontend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/frontend/nginx/configmap.yaml") . | sha256sum }}
    spec:
{{- include "tm-cloud.imagePullSecrets" . | indent 6 }}
      containers:
      - name: nginx
        image: "nginx:stable"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config
        configMap:
          name: {{ include "tm-cloud.frontend.fullname" . }}-nginx-config
{{- end }}
