apiVersion: v1
kind: Service
metadata:
  name: {{ include "tm-cloud.ghbackend.fullname" . }}
  labels:
    {{- include "tm-cloud.ghbackend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    {{- include "tm-cloud.ghbackend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
