apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tm-cloud.bridgecatalogentries.fullname" . }}
  labels:
    {{- include "tm-cloud.bridgecatalogentries.labels" . | nindent 4 }}
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "tm-cloud.bridgecatalogentries.fullname" . }}
