apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "istio-operator.fullname" . }}
  labels:
    {{- include "istio-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "istio-operator.fullname" . }}
  namespace: {{ .Values.operatorNamespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "istio-operator.fullname" . }}
