apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-operator.fullname" . }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "istio-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
    protocol: TCP
  selector:
    {{- include "istio-operator.selectorLabels" . | nindent 4 }}
