apiVersion: v1
kind: Service
metadata:
  name: {{ include "tm-cloud.frontend.fullname" . }}
  labels:
    {{- include "tm-cloud.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    {{- include "tm-cloud.frontend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tm-cloud.frontend.fullname" . }}-k8s
  labels:
    {{- include "tm-cloud.frontend.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: kubernetes.default
  ports:
  - port: 443
