apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tm-cloud.knative-targets.fullname" . }}
  labels:
    {{- include "tm-cloud.knative-targets.labels" . | nindent 4 }}
rules:
  # Manage receive-adapters
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update

# Manage dogstatsd agents for the Datadog target
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update

- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update

  # Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - update
  - patch

  # Read secrets
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

  # Read controller configurations
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - {{ include "tm-cloud.knative-configs.fullname" . }}-config-logging
  - {{ include "tm-cloud.knative-configs.fullname" . }}-config-observability
  - {{ include "tm-cloud.knative-configs.fullname" . }}-config-leader-election
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

  # Manage resource-specific ServiceAccounts and RoleBindings
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  resourceNames:
  - tektontarget-adapter
  verbs:
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  resourceNames:
  - tektontarget-adapter
  verbs:
  - update
  - delete

  # Tekton reaper
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - list

  # Read and manage status for target resources
- apiGroups:
  - targets.triggermesh.io
  resources:
  - awsdynamodbtargets
  - awskinesistargets
  - awslambdatargets
  - awss3targets
  - awssnstargets
  - awssqstargets
  - confluenttargets
  - datadogtargets
  - elasticsearchtargets
  - googlesheettargets
  - googlecloudstoragetargets
  - hasuratargets
  - httptargets
  - infratargets
  - jiratargets
  - logztargets
  - oracletargets
  - salesforcetargets
  - sendgridtargets
  - slacktargets
  - splunktargets
  - tektontargets
  - twiliotargets
  - uipathtargets
  - zendesktargets
  verbs:
  - list
  - watch
  - get

- apiGroups:
  - targets.triggermesh.io
  resources:
  - awsdynamodbtargets/status
  - awskinesistargets/status
  - awslambdatargets/status
  - awss3targets/status
  - awssnstargets/status
  - awssqstargets/status
  - confluenttargets/status
  - datadogtargets/status
  - elasticsearchtargets/status
  - googlesheettargets/status
  - googlecloudstoragetargets/status
  - hasuratargets/status
  - httptargets/status
  - infratargets/status
  - jiratargets/status
  - logztargets/status
  - oracletargets/status
  - salesforcetargets/status
  - sendgridtargets/status
  - slacktargets/status
  - splunktargets/status
  - tektontargets/status
  - twiliotargets/status
  - uipathtargets/status
  - zendesktargets/status
  verbs:
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tektontarget-adapter
  labels:
    {{- include "tm-cloud.knative-targets.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tekton.dev
  resources:
  - taskruns
  - pipelineruns
  verbs:
  - create
  - list
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tm-cloud.knative-targets.fullname" . }}-addressable-resolver
  labels:
    duck.knative.dev/addressable: 'true'
    {{- include "tm-cloud.knative-targets.labels" . | nindent 4 }}
rules:
- apiGroups:
  - targets.triggermesh.io
  resources:
  - awsdynamodbtargets
  - awskinesistargets
  - awslambdatargets
  - awss3targets
  - awssnstargets
  - awssqstargets
  - confluenttargets
  - datadogtargets
  - elasticsearchtargets
  - googlesheettargets
  - googlecloudstoragetargets
  - hasuratargets
  - httptargets
  - infratargets
  - jiratargets
  - logztargets
  - salesforcetargets
  - oracletargets
  - sendgridtargets
  - slacktargets
  - splunktargets
  - tektontargets
  - twiliotargets
  - uipathtargets
  - zendesktargets
  verbs:
  - get
  - list
  - watch
